{
  "namespace": "org.torrust.tracker",
  "version": "1.0.0",
  "tracker": {
    "global": {
      "tracker_mode": "listed",
      "log_filter_level": "info",
      "external_ip": null,
      "on_reverse_proxy": false
    },
    "common": {
      "announce_interval_seconds": 120,
      "announce_interval_seconds_minimum": 120,
      "peer_timeout_seconds_maximum": 900,
      "enable_tracker_usage_statistics": true,
      "enable_persistent_statistics": false,
      "cleanup_inactive_peers_interval_seconds": 600,
      "enable_peerless_torrent_pruning": false
    },
    "database": {
      "driver": "sqlite3",
      "sql_lite_3_db_file_path": "data.db",
      "my_sql_connection_url": null
    },
    "service": {
      "default_api": {
        "enabled": false,
        "display_name": "HTTP API (default)",
        "service": "api",
        "socket": "127.0.0.1:1212",
        "tls": null,
        "access_tokens": {
          "admin": "password"
        }
      },
      "default_http": {
        "enabled": false,
        "display_name": "HTTP (default)",
        "service": "http",
        "socket": "0.0.0.0:6969",
        "tls": null,
        "access_tokens": null
      },
      "default_tls": {
        "enabled": false,
        "display_name": "TLS (default)",
        "service": "http",
        "socket": "0.0.0.0:6969",
        "tls": {
          "certificate_file_path": "",
          "key_file_path": ""
        },
        "access_tokens": null
      },
      "default_udp": {
        "enabled": false,
        "display_name": "UDP (default)",
        "service": "udp",
        "socket": "0.0.0.0:6969",
        "tls": null,
        "access_tokens": null
      }
    }
  }
}