[core]
db_path = "/var/lib/torrust/tracker/database/sqlite3.db"

[[udp_trackers]]
enabled = true

[[http_trackers]]
enabled = true
ssl_cert_path = "/var/lib/torrust/tracker/tls/localhost.crt"
ssl_key_path = "/var/lib/torrust/tracker/tls/localhost.key"

[http_api]
ssl_cert_path = "/var/lib/torrust/tracker/tls/localhost.crt"
ssl_key_path = "/var/lib/torrust/tracker/tls/localhost.key"

[health_check_api]
# Must be bound to wildcard IP to be accessible from outside the container
bind_address = "0.0.0.0:1313"
