[core.database]
path = "/var/lib/torrust/tracker/database/sqlite3.db"

[[udp_trackers]]
enabled = true

[[http_trackers]]
enabled = true

[health_check_api]
# Must be bound to wildcard IP to be accessible from outside the container
bind_address = "0.0.0.0:1313"
