[global]
log_filter_level = "Info"
external_ip = ""
on_reverse_proxy = false

[common]
tracker_mode = "listed"
announce_interval = 120
min_announce_interval = 120
max_peer_timeout = 900
tracker_usage_statistics = true
persistent_torrent_completed_stat = false
inactive_peer_cleanup_interval = 600
remove_peerless_torrents = false

[common.database]
db_driver = "Sqlite3"
db_path = "data.db"

[service.0]
display_name = "HTTP API (default)"
service = "API"
enabled = false
socket = "127.0.0.1:1212"

[service.0.access_tokens]
admin = "password"

[service.1]
display_name = "UDP (default)"
service = "UDP"
enabled = false
socket = "0.0.0.0:6969"

[service.2]
display_name = "HTTP (default)"
service = "HTTP"
enabled = false
socket = "0.0.0.0:6969"

[service.3]
display_name = "TLS (default)"
service = "HTTP"
enabled = false
socket = "0.0.0.0:6969"

[service.3.tls]
certificate_file_path = ""
key_file_path = ""
