[package]
description = "A library registering services"
keywords = ["library", "registry", "service"]
name = "torrust-tracker-registry"
readme = "README.md"

authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
torrust-tracker-services = { version = "3.0.0-beta-develop", path = "../services" }

derive_more = { version = "1", features = ["constructor", "deref", "deref_mut"] }
futures = "0"
pin-project-lite = "0"
thiserror = "1"
tokio = { version = "1", features = ["macros", "sync"] }
tracing = "0"
